### ISSUE TITLE
Bug with SA scorer

### ISSUE THREAD

**Issue by RMeli** [jrwnter/mso#5]
The `sascorer` in the following code does not seem to be imported:

https://github.com/jrwnter/mso/blob/35f78acb13bd0f6cd8ece8b0d9787f49aa662678/mso/objectives/mol_functions.py#L85-L93

Given that all exceptions are caught, this fails silently and `sa_score` always returns a score of `0`.

**Comment by Pixelatory** [comment]
(Edit) I realized that MSO includes the file for SA score. Not sure how I didn't find this before since it's not a particularly large file structure.

You can get SA score to work by doing the following:
- Remove the default import for SA score
- Write this: `import mso.data.sascorer as sascorer`

That seemed to work for me, and I hope it does for you but if not message back here.

**Comment by RMeli** [comment]
Thanks @Pixelatory . I actually fixed this issue in PR #6 but I closed it as stale after a few months since the repository seems to be no longer maintained.

**Comment by Pixelatory** [comment]
Oh nice! Yeah it doesn't seem like it is
